### ISSUE TITLE
Usage with a top-down view

### ISSUE THREAD

**Issue by auesro** [YttriLab/B-SOID#2]
Dear @runninghsus 

Thanks for making this code available, I think it will be a great help for many including myself.

I am trying to adapt the code to work with a top-down view of mice in their home cages, where the main problem is not having any of the paws in view for most of the time. So I have been going through your code and came across [this](https://github.com/YttriLab/B-SOID/blob/7ac62590d3598182654662c0b5df226929fb58ca/bsoid/dlc_preprocess.m#L29). Does it mean that after running `dlc_preprocess` the hind paws positions are not used anymore? Or that you dont filter them because they are always in view and hence tracked by DeepLabCut with high confidence anyway?

Also, do you have any recommendations regarding what points to label in the mouse for use with a top-down view?

Thanks a lot,

Augusto

**Comment by runninghsus** [comment]
Hi Augusto,

Thank you for your issue. I apologize that the comment was an earlier version. It has been fixed now. But to your point, I do pre-process all of the data with a likelihood threshold value, which I now am working on **data-driven determination for likelihood threshold value for version 1.1 (stay tuned!), as well as an argument that could specify top-down versus bottom-up view.** 

I do not know how many points you have labeled from top-down view, but I'd imagine you be able to consistently track _snout/head/ears, center of body, proximal tail, and distal tail._

You can adapt the code to extract features that does not involve the paws for behavioral segmentation. For example, **body length** (head to body center and/or head to proximal tail), **speed** (head, body center or proximal tail), and **angle** (head to center body angle, body to proximal tail angle, or head to proximal tail angle) will be selectively fed into the algorithm. All the rest will still work to segment behaviors, even from top-down view.

Let me know if you have any further questions or if any of this is unclear.

Good to know more people are thinking about using this to advance behavioral science! 

Alex

**Comment by auesro** [comment]
Hi Alex,

No apologies needed.
Looking forward to version 1.1!

Yea, I can easily label: head, ears, body center, base and tip of the tail. I was just wondering how much of the behavioral prediction depends on data coming from tracking the paws. In my case, I want to quantify behaviors like scratching, which without the hindpaw data might be difficult... but lets see what B-SOID has to say about it.

I will get to it and come back to you in case of doubts!

Thanks!

A

**Comment by auesro** [comment]
Hi again,

Another question:
What would you recommend as a strategy for DLC labeling of body parts?
-1) Label only visible body parts
-2) Label both visible and occluded body parts
Since dlc_preprocess will fill in missing data through a math calculation, my guess is that it would be better to try and train DLC to guess the location of that body part so that we reduce the number of missing data points to average through, right?

Thanks!

A

**Comment by runninghsus** [comment]
> Hi Alex,
> 
> No apologies needed.
> Looking forward to version 1.1!
> 
> Yea, I can easily label: head, ears, body center, base and tip of the tail. I was just wondering how much of the behavioral prediction depends on data coming from tracking the paws. In my case, I want to quantify behaviors like scratching, which without the hindpaw data might be difficult... but lets see what B-SOID has to say about it.
> 
> Also, you mention [here](https://github.com/YttriLab/B-SOID/blob/master/docs/bsoid_gmm.md#bsoid_gmmm) that data input for BSOID_GMM.m is
> 
> > A cell-array containing either one or multiple rodents' estimated positions
> 
> How should DATA be organized if I have 2 animals in the video? The second animal should be in a different cell? Do you have any example data for that case?
> 
> I will get to it and come back to you in case of doubts!
> 
> Thanks!
> 
> A

**Comment by runninghsus** [comment]
Hi Augusto,

Yes you might be right that a combination of body kinematic changes would isolate scratching without the need to label it (which is the beauty of this algorithm). Let's see if it can!

I am not sure if I understood your question. I came up with two interpretation. 1. Two or more animals sequentially in a single video. 2. Simultaneous recording of two animals (social context). 

I can help with 1, not 2 at the moment. I am working on my algorithm in cases where there are more than 1 animal and will be a separate branch from this. For the one I can help out: it does not matter if you have two animals in the same video. `DATA` in a cell-array format allows you to merge multiple .csv files together for analyses. For example, if you have more than 1 .csv file (because you analyzed multiple animals on different days, different times, etc.) generated from DLC, the idea is that you can combine all the natural statistics from different sized animals to segment behaviors more robustly across dataset. That being said, if you just have 1 .csv file containing more than 1 animal, it'd reduce the run-time (no for-loop required). 

I do not have example data for 1 or 2. I am working on 2 for the next version of this code.

For your other question, if I understood you correctly, is asking about how labeling in DLC interacts with dlc_preprocess. Short answer is you do want to label body parts that allows DLC to at least have high enough confidence to guess when its partially occluded. So something in between the two options you posed. You **do not want to label completely occluded body parts as it will then be trained on completely irrelevant pixels**. You **do want to label the partially occluded body parts to help your training** (it learns to associate partially occluded structures as complete structures). Just to reiterate, if there is partial exposure that you can sort of make out, then yes, label them so the computer can generate a point with high enough confidence that won't be manipulated as much by `dlc_preprocess.m`. The point of the smoothing interpretation is to treat completely occluded signals (by looking at the confidence over-time) as opposed to mislabeling by chance (usually won't sustain over time) as absence of signal. 

Hope this helps!
Let me know if you have any further questions before I close this issue!

Alex

**Comment by auesro** [comment]
Hi Alex,

I meant the interpretation 2, good to know you are working on it. Looking forward!

Regarding my other question, you kind of answered it but let me try to be more clear: 

What would you suggest would be the best strategy if you had (remember, top down view) a body part (paws in this case) that are most of the time occluded? Label them in DLC by guessing  its location despite the fact you cannot see them in the frame and let DLC learn to do the same OR only label them when they are visible and then let dlc_preprocess.m to fill in those missing data, which would represent a substantial amount of data points given that you only see the paws in a top down view very rarely now and then.

I hope I made myself more clear now ;)

Thanks!

A

**Comment by runninghsus** [comment]
Hi Augusto,

It will require some refinement if you are mostly labeling a certain part of the torso, with only a few frames labeling when the paws are seen. To rephrase, you would need to get enough samples of actual paws to offset the rigid training of torso edge. 

However, it really depends on your question if that makes jitters in identifying when the paw is seen really matters that much. If you are trying to use B-SOiD to extract spontaneous scratch/groom with the forepaws, if you look at the video and can interpret scratch, my guess is that B-SOiD can too. Just a matter of what you features you are considering when you differentiate scratch from a rear or scrunch (where body lengths are all shortened and grossly stationed). I think you can potentially be able to cluster scratches from rears or scrunch by snout speed itself. 
The idea behind B-SOiD is dissecting how we look at videos and are able to determine 3-D behaviors. It should be capable of interpreting 3-D behaviors given sufficient information.

Let me know what you think,


Alex Hsu

**Comment by auesro** [comment]
Hi Alex,

I will give a try to both options. I trained a DLC network labeling only the body parts I can clearly see and I am training now another one where I labeled all body parts on all frames "guessing" the position of the occluded ones. So I will try both outputs in B-SOID and see what happens.

I agree with your analysis, my goal so far is to quantify scratching with the hindlimbs and since I can clearly see it in the video. Lets see if I am providing enough info for B-SOID to do it too.

I will report back with results!

Thanks,

A

**Comment by runninghsus** [comment]
Sounds good. Join our [slack group](https://b-soidb-side.slack.com/)!
We can chat there for data related questions.

**Comment by auesro** [comment]
Dear Alex, stupid question here...how do I join your slack group?

**Comment by runninghsus** [comment]
Email me and I will send you an invitation. ahsu2@andrew.cmu.edu
