### ISSUE TITLE
Use with 3d CSV files

### ISSUE THREAD

**Issue by PolarBean** [YttriLab/B-SOID#3]
This repo looks fantastic :) I'm curious as to whether the code will work with 3d csv files now that DLC has multi-cam support.

Thank you in advance,

Harry

**Comment by runninghsus** [comment]
Hi Harry,

I'd be interested to run some tests on 3d .csv files! I have yet to collect any and am willing to run some tests if you have data you are willing to share.

Theoretically, it should work better, as currently signal occlusion can mean many behaviors. The same concept should hold that behaviors are statistically different multi-dimensional features.

Let me know if you are interested in providing data for testing; Otherwise, I would recommend giving the algorithm an in-depth look and tweak it yourself. 

You can contact me personally @ ahsu2@andrew.cmu.edu

Best,

Alex

**Comment by PolarBean** [comment]
ah that would be fantastic. We will begin collecting 3d footage in late January/ early February and I would be more than happy to share the 3d csvs :). in the mean time I will look into your algorithm in more depth.
Thank you!

all the best, 

Harry

**Comment by runninghsus** [comment]
Sounds good!
We will have a few bug fixes and slightly more user-friendly version (1.1) released in a couple weeks! Stay tuned for that as well!
Looking forward to support 3d csvs!

Alex
